name: Release master branch

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubectl_version:
          - 1.19.0
          - 1.18.8
          - 1.17.11
          - 1.16.14
          - 1.15.12
          - 1.14.10
          - 1.13.12
    steps:
      - uses: actions/checkout@v1

      - name: Semantic Release Config
        run: |
          echo '{
                   "tagFormat":"v${version}",
                   "plugins": [
                      "@semantic-release/commit-analyzer",
                      "@semantic-release/release-notes-generator",
                      "@semantic-release/changelog",
                      "@semantic-release/github"
                   ]
                }
          '> .releaserc
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          branches: 'master'
          semantic_version: 17.1.1
          extra_plugins: |
            @semantic-release/commit-analyzer@8.0.1
            @semantic-release/release-notes-generator@9.0.0
            @semantic-release/changelog@5.0.0
            @semantic-release/github@7.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --build-arg KUBECTL_VERSION=${{ matrix.kubectl_version }} --tag germainlefebvre4/ns-killer:${{ steps.semantic.outputs.new_release_version }}-kubectl-${{ matrix.kubectl_version }}
      - name: Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: germainlefebvre4/ns-killer:${{ steps.semantic.outputs.new_release_version }}-kubectl-${{ matrix.kubectl_version }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --build-arg KUBECTL_VERSION=${{ matrix.kubectl_version }} --tag germainlefebvre4/ns-killer:latest-kubectl-${{ matrix.kubectl_version }}
      - name: Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: germainlefebvre4/ns-killer:latest-kubectl-${{ matrix.kubectl_version }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
